api/urls.py
from django.conf.urls import url, include
from django.urls import path
from api import views

urlpatterns = [
    path('', views.ListTodo.as_view()),
    path('<int:pk>/', views.DetailTodo.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
    path('webpage/', include(('webpage.urls', 'webpage'), namespace='webpage')),
    path('', include(('api.urls', 'api'), namespace='api'))
]

todo/urls.py
from django.urls import path, include
from todo.views import createToDo, archiveToDo, deleteToDo

urlpatterns = [
    path('create', createToDo, name='create'),
    path('archive', archiveToDo, name='archive'),
    path('delete', deleteToDo, name='delete')
]

webpage/urls.py
from django.urls import path, include
from webpage.views import index

urlpatterns = [
    path('', index)
]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class ToDo(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.TextField(max_length=20, null=False)
    description = models.TextField(max_length=144, null=True)
    archived = models.BooleanField(default=False, null=False)

api/views.py
from rest_framework import generics
from todo.models import ToDo
from api.serializers import ToDoSerializer


class ListTodo(generics.ListCreateAPIView):
    queryset = ToDo.objects.all()
    serializer_class = ToDoSerializer

class DetailTodo(generics.RetrieveUpdateDestroyAPIView):
    queryset = ToDo.objects.all()
    serializer_class = ToDoSerializer

todo/views.py
from django.shortcuts import render, redirect
from todo.models import ToDo

# Create your views here.

def createToDo(request):

    if (request.POST):
        user = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')
        archived = False
        todo = ToDo(user=user, title=title, description=description, archived=archived)
        todo.save()

    return redirect('/webpage')

def archiveToDo(request):

    if (request.POST):

        todo = ToDo.objects.get(id=request.POST.get('id'))

        if (request.user == todo.user):
            todo.archived = True
            todo.save()

    return redirect('/webpage')

def deleteToDo(request):
    print(request)
    if (request.POST):

        todo = ToDo.objects.get(id=request.POST.get('id'))

        if (request.user == todo.user):
            todo.delete()

    return redirect('/webpage')

webpage/views.py
from django.shortcuts import render
from todo.models import ToDo

# Create your views here.

def index(request):

    context = {'todos' : ToDo.objects.all().filter(archived=False, user=request.user)}

    return render(request, 'webpage/index.html', context)

webpage/templates/webpage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>ToDo</title>
  <link rel="stylesheet" href="{% static 'webpage/css/index.css' %}" type="text/css">
</head>

<body>
  <div>
    <form action="{% url 'todo:create' %}" method="post">
      {% csrf_token %}
      <input type="text" name="title" id="">
      <input type="text" name="description" id="">
      <button type="submit">Send</button>
    </form>
  </div>
  <div class="container">
    {% for x in todos %}
    <div class="todo">
      <h1>{{ x.title }}</h1>
      <h2>{{ x.date }}</h2>
      <div class="container">
        <form action="{% url 'todo:archive' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ x.id }}">
          <button class="button" type="submit">Archive</button>
        </form>
        <form action="{% url 'todo:delete' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ x.id }}">
          <button class="button" type="submit">Delete</button>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
</body>

</html>